### ISSUE TITLE
Fail to install on Hass.io 0.93.1

### ISSUE THREAD

**Issue by allenrong88** [guidone/node-red-contrib-chatbot#310] opened 2019-05-22 13:58 UTC
Recently upgraded Hass.io to the latest release 0.93.1 and get Node Red successfully installed. When I tried installing node-red-contrib-chatbot and it failed all the times. Is it the version thing? Notice here that 0.16.8 is the latest release but 0.16.6 is the one it tried to install in Node Red.

Anyone has the same issue?

**Comment by guidone** [comment] 2019-05-22 15:14
Which versione of node is installed?

**Comment by allenrong88** [comment] 2019-05-23 01:28
Thanks for your reply.

I can check it tonight to see which version. My hass.io was a brand new image, I re-imaged it last night, so I assume Node Red I installed from add-on store should be the latest one.

**Comment by allenrong88** [comment] 2019-05-25 05:11
Checked my NODE RED version just now, which is 3.1.1.

**Comment by guidone** [comment] 2019-06-20 07:27
Do you still have this problem?

**Comment by Dmxsir** [comment] 2019-06-27 19:26
I also have a few problem.
few error and warning .

Trying to install it on **HASSIO** v0.95 and `**NOD-RED**` adds-on  `v4.0.1`

```[err]  Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.21.1/node-v64-linux-arm-musl.tar.gz```

here is the full log
https://0bin.net/paste/tivT40DekhWaHerY#mdLOVd5QXytdGcJ3xJizlxj5Dss6ei8rl6wHA946Rxt

**Comment by CashWilliams** [comment] 2021-04-24 04:58
Duplicate of #423

**Comment by CashWilliams** [comment] 2021-04-24 04:58
#473 is duplicate

**Closed** 2023-01-25 16:21 UTC
